import type { Mission } from '@/lib/types';

/**
 * Limited seasonal collection. These use the app's advanced tier as the
 * product-facing C1 equivalent and remain full missions with stable IDs.
 */
export const AUTUMN_MISSIONS: Mission[] = [
  {
    id: 'mushroom-foraging-b1',
    title: 'Mushroom Foraging',
    tagline: 'Discuss forest ecology and responsible foraging with a qualified guide.',
    category: 'Nature & outdoors',
    icon: 'compass',
    level: 'advanced',
    minutes: 30,
    accent: 'magenta',
    where: 'A guided autumn forest walk with a qualified local expert.',
    reflectionFocus: 'discuss responsible foraging and clarify safety advice in German',
    realLifeSteps: [
      'Join a walk led by a qualified local guide; never identify mushrooms from this lesson alone.',
      'Ask how the forest ecosystem changes during autumn.',
      'Clarify one rule about collecting, protected areas, or poisonous species.',
      'Paraphrase the guide’s answer to check that you understood it correctly.',
      'Leave every unidentified mushroom untouched and thank the guide for their expertise.',
    ],
    vocab: [
      {
        id: 'autumn-mushroom-1',
        de: 'das Ökosystem',
        en: 'ecosystem',
        note: 'Useful when connecting individual species with the wider forest.',
      },
      {
        id: 'autumn-mushroom-2',
        de: 'das Bestimmungsmerkmal',
        en: 'identifying characteristic',
        note: 'A technical feature used by experts to distinguish species.',
      },
      {
        id: 'autumn-mushroom-3',
        de: 'giftig / genießbar',
        en: 'poisonous / edible',
        note: 'Only a qualified expert should make this distinction in practice.',
      },
      {
        id: 'autumn-mushroom-4',
        de: 'unter Naturschutz stehen',
        en: 'to be protected by conservation law',
        note: 'Use it to ask whether collecting a species is permitted.',
      },
      {
        id: 'autumn-mushroom-5',
        de: 'der Fruchtkörper',
        en: 'fruiting body',
        note: 'The visible part of a fungus above the ground.',
      },
      {
        id: 'autumn-mushroom-6',
        de: 'im Zweifelsfall',
        en: 'when in doubt',
        note: 'A concise way to introduce the safest course of action.',
      },
      {
        id: 'autumn-mushroom-7',
        de: 'Habe ich Sie richtig verstanden, dass …?',
        en: 'Have I understood you correctly that …?',
        note: 'A C1-level clarification phrase for checking complex advice.',
      },
      {
        id: 'autumn-mushroom-8',
        de: 'Davon ist dringend abzuraten.',
        en: 'That is strongly discouraged.',
        note: 'Formal wording for a clear warning.',
      },
    ],
    conversationSimulation: [
      {
        id: 'autumn-mushroom-c1',
        speaker: 'partner',
        de: 'Bevor wir losgehen: Gesammelt wird heute ausschließlich unter meiner Anleitung.',
        en: 'Before we set off: today, collecting is done exclusively under my guidance.',
      },
      {
        id: 'autumn-mushroom-c2',
        speaker: 'you',
        de: 'Habe ich Sie richtig verstanden, dass wir unbekannte Pilze grundsätzlich stehen lassen?',
        en: 'Have I understood correctly that we always leave unknown mushrooms untouched?',
      },
      {
        id: 'autumn-mushroom-c3',
        speaker: 'partner',
        de: 'Genau. Selbst ähnliche Arten können völlig unterschiedliche Wirkungen haben.',
        en: 'Exactly. Even similar species can have completely different effects.',
      },
      {
        id: 'autumn-mushroom-c4',
        speaker: 'you',
        de: 'Welche Rolle spielen Pilze denn für das Ökosystem des Waldes?',
        en: 'What role do fungi play in the forest ecosystem?',
      },
      {
        id: 'autumn-mushroom-c5',
        speaker: 'partner',
        de: 'Sie zersetzen organisches Material und versorgen viele Bäume mit Nährstoffen.',
        en: 'They decompose organic matter and supply many trees with nutrients.',
      },
      {
        id: 'autumn-mushroom-c6',
        speaker: 'you',
        de: 'Dann wäre wahlloses Sammeln nicht nur riskant, sondern auch ökologisch problematisch.',
        en: 'Then indiscriminate collecting would be not only risky but ecologically problematic.',
      },
      {
        id: 'autumn-mushroom-c7',
        speaker: 'partner',
        de: 'Richtig. Im Zweifelsfall gilt immer: anschauen, fotografieren und stehen lassen.',
        en: 'Correct. When in doubt: look, photograph, and leave it in place.',
      },
      {
        id: 'autumn-mushroom-c8',
        speaker: 'you',
        de: 'Das ist eindeutig. Danke, dass Sie die Regel so nachvollziehbar erklärt haben.',
        en: 'That is clear. Thank you for explaining the rule so comprehensibly.',
      },
    ],
    practiceQuestions: [
      {
        id: 'autumn-mushroom-q1',
        kind: 'multiple-choice',
        prompt: 'Which sentence best checks your understanding of the guide’s safety rule?',
        options: [
          'Habe ich Sie richtig verstanden, dass wir unbekannte Pilze stehen lassen?',
          'Ich nehme diesen Pilz einfach mit.',
          'Pilze interessieren mich eigentlich nicht.',
        ],
        answerIndex: 0,
        explanation: 'The first option paraphrases the rule and explicitly asks for confirmation.',
      },
      {
        id: 'autumn-mushroom-q2',
        kind: 'fill-blank',
        prompt: 'Complete the expert safety phrase.',
        sentence: 'Im ___ lassen wir den Pilz stehen.',
        answer: 'Zweifelsfall',
        alternatives: ['zweifelsfall'],
        explanation: '„Im Zweifelsfall“ means “when in doubt” and introduces the safer option.',
      },
      {
        id: 'autumn-mushroom-q3',
        kind: 'write-sentence',
        prompt: 'Write a sentence connecting mushroom collecting with forest conservation.',
        mustInclude: ['Ökosystem'],
        sample: 'Verantwortungsvolles Sammeln schützt das empfindliche Ökosystem des Waldes.',
        explanation: 'Advanced language links the action to its wider ecological consequence.',
      },
    ],
    badge: {
      title: 'Waldkenner',
      emoji: '🍄',
      description: 'Discussed forest ecology and responsible foraging with an expert.',
    },
  },
  {
    id: 'apple-cider-c1',
    title: 'Apple Cider Culture',
    tagline: 'Compare regional apple traditions and discuss how craft producers work.',
    category: 'Food & culture',
    icon: 'utensils',
    level: 'advanced',
    minutes: 30,
    accent: 'coral',
    where: 'An orchard shop, weekly market, or autumn harvest festival.',
    reflectionFocus: 'compare regional apple traditions with a producer or market vendor',
    realLifeSteps: [
      'Find an orchard stall or producer selling regional apple juice or cider products.',
      'Ask which apple varieties shape the flavour and why they were chosen.',
      'Compare an alcohol-free product with a traditional regional speciality.',
      'Ask how this year’s harvest affected taste, price, or production.',
      'Summarise one tradition in your own words before you leave.',
    ],
    vocab: [
      {
        id: 'autumn-cider-1',
        de: 'die Streuobstwiese',
        en: 'traditional meadow orchard',
        note: 'An orchard landscape with scattered, often older fruit trees.',
      },
      {
        id: 'autumn-cider-2',
        de: 'die Apfelsorte',
        en: 'apple variety',
        note: 'Ask which varieties create sweetness, acidity, or tannins.',
      },
      {
        id: 'autumn-cider-3',
        de: 'naturtrüb',
        en: 'naturally cloudy',
        note: 'Common on juice labels when fine fruit particles remain.',
      },
      {
        id: 'autumn-cider-4',
        de: 'die Kelterei',
        en: 'cider press / pressing facility',
        note: 'The place where fruit is pressed and processed.',
      },
      {
        id: 'autumn-cider-5',
        de: 'herb / säuerlich',
        en: 'tart / slightly acidic',
        note: 'Useful tasting words that go beyond sweet or sour.',
      },
      {
        id: 'autumn-cider-6',
        de: 'der Jahrgang',
        en: 'vintage / harvest year',
        note: 'Use it to discuss how growing conditions change a product.',
      },
      {
        id: 'autumn-cider-7',
        de: 'Worin unterscheidet sich … von …?',
        en: 'How does … differ from …?',
        note: 'A precise comparison structure for an informed conversation.',
      },
      {
        id: 'autumn-cider-8',
        de: 'Das hängt maßgeblich davon ab, …',
        en: 'That largely depends on …',
        note: 'A formal connector for explaining a decisive factor.',
      },
    ],
    conversationSimulation: [
      {
        id: 'autumn-cider-c1',
        speaker: 'you',
        de: 'Worin unterscheidet sich Ihr naturtrüber Saft von einem industriell hergestellten?',
        en: 'How does your naturally cloudy juice differ from an industrially produced one?',
      },
      {
        id: 'autumn-cider-c2',
        speaker: 'partner',
        de: 'Wir verarbeiten alte Sorten direkt nach der Ernte und filtern nur sehr wenig.',
        en: 'We process heritage varieties directly after harvest and filter very little.',
      },
      {
        id: 'autumn-cider-c3',
        speaker: 'you',
        de: 'Schmeckt man den diesjährigen Jahrgang deutlich heraus?',
        en: 'Can you clearly taste this year’s vintage?',
      },
      {
        id: 'autumn-cider-c4',
        speaker: 'partner',
        de: 'Ja. Durch den kühlen Sommer ist er etwas säuerlicher und besonders aromatisch.',
        en: 'Yes. Because of the cool summer, it is slightly more acidic and especially aromatic.',
      },
      {
        id: 'autumn-cider-c5',
        speaker: 'you',
        de: 'Welche Bedeutung haben Streuobstwiesen für Ihren Betrieb?',
        en: 'How important are traditional meadow orchards to your business?',
      },
      {
        id: 'autumn-cider-c6',
        speaker: 'partner',
        de: 'Sie liefern nicht nur Obst, sondern erhalten auch Lebensräume für viele Arten.',
        en: 'They provide not only fruit but also preserve habitats for many species.',
      },
      {
        id: 'autumn-cider-c7',
        speaker: 'you',
        de: 'Die regionale Tradition hat also zugleich einen ökologischen Nutzen.',
        en: 'So the regional tradition also has an ecological benefit.',
      },
      {
        id: 'autumn-cider-c8',
        speaker: 'partner',
        de: 'Genau. Deshalb arbeiten wir eng mit den örtlichen Obstbauern zusammen.',
        en: 'Exactly. That is why we work closely with local fruit growers.',
      },
    ],
    practiceQuestions: [
      {
        id: 'autumn-cider-q1',
        kind: 'multiple-choice',
        prompt: 'What does „naturtrüb“ tell you about an apple juice?',
        options: [
          'It is minimally filtered and naturally cloudy.',
          'It contains no apples.',
          'It must be imported.',
        ],
        answerIndex: 0,
        explanation: '„Naturtrüb“ describes juice that retains natural suspended fruit particles.',
      },
      {
        id: 'autumn-cider-q2',
        kind: 'fill-blank',
        prompt: 'Complete the comparison question.',
        sentence: 'Worin ___ sich diese Apfelsorte von der anderen?',
        answer: 'unterscheidet',
        alternatives: [],
        explanation: 'The reflexive verb is „sich unterscheiden“; the subject is singular here.',
      },
      {
        id: 'autumn-cider-q3',
        kind: 'write-sentence',
        prompt: 'Ask how the harvest year influenced the flavour.',
        mustInclude: ['Jahrgang'],
        sample: 'Inwiefern hat der diesjährige Jahrgang den Geschmack beeinflusst?',
        explanation: '„Inwiefern“ invites a nuanced explanation rather than a yes-or-no answer.',
      },
    ],
    badge: {
      title: 'Apfelkenner',
      emoji: '🍎',
      description: 'Compared regional apple traditions with a local producer.',
    },
  },
  {
    id: 'farmers-market-c1',
    title: 'Farmers’ Market Mastery',
    tagline: 'Navigate a busy market and discuss provenance, seasonality, and fair pricing.',
    category: 'Shopping & errands',
    icon: 'users',
    level: 'advanced',
    minutes: 30,
    accent: 'sky',
    where: 'A Hamburg Wochenmarkt with regional autumn produce.',
    reflectionFocus: 'discuss provenance, seasonality, and fair pricing with a market vendor',
    realLifeSteps: [
      'Visit a weekly market when vendors have time for a short conversation.',
      'Ask where one seasonal product was grown and how it reached the stall.',
      'Discuss why its price or availability differs from supermarket produce.',
      'Request a recommendation for preparing or storing it without waste.',
      'Buy only what you need and recap the vendor’s key advice.',
    ],
    vocab: [
      {
        id: 'autumn-market-1',
        de: 'die Herkunft',
        en: 'origin / provenance',
        note: 'A direct way to ask where food comes from.',
      },
      {
        id: 'autumn-market-2',
        de: 'saisonal verfügbar',
        en: 'seasonally available',
        note: 'Describes produce limited to part of the year.',
      },
      {
        id: 'autumn-market-3',
        de: 'die Lieferkette',
        en: 'supply chain',
        note: 'Useful when comparing direct sales with retail distribution.',
      },
      {
        id: 'autumn-market-4',
        de: 'der Erzeugerbetrieb',
        en: 'producing farm / producer business',
        note: 'More precise than simply saying „Bauernhof“.',
      },
      {
        id: 'autumn-market-5',
        de: 'aussortieren',
        en: 'to sort out / reject',
        note: 'Often used when discussing cosmetic standards for produce.',
      },
      {
        id: 'autumn-market-6',
        de: 'preislich gerechtfertigt',
        en: 'justified in terms of price',
        note: 'A diplomatic phrase for discussing value rather than haggling.',
      },
      {
        id: 'autumn-market-7',
        de: 'Könnten Sie näher erläutern, …?',
        en: 'Could you explain in more detail …?',
        note: 'A polite advanced prompt that invites expert detail.',
      },
      {
        id: 'autumn-market-8',
        de: 'unter diesen Voraussetzungen',
        en: 'under these conditions',
        note: 'Use it to draw a conclusion from what the vendor explained.',
      },
    ],
    conversationSimulation: [
      {
        id: 'autumn-market-c1',
        speaker: 'you',
        de: 'Könnten Sie näher erläutern, woher dieser Kürbis stammt?',
        en: 'Could you explain in more detail where this pumpkin comes from?',
      },
      {
        id: 'autumn-market-c2',
        speaker: 'partner',
        de: 'Er kommt aus unserem Erzeugerbetrieb südlich von Hamburg und wurde gestern geerntet.',
        en: 'It comes from our farm south of Hamburg and was harvested yesterday.',
      },
      {
        id: 'autumn-market-c3',
        speaker: 'you',
        de: 'Ist die kurze Lieferkette der Hauptgrund für den höheren Preis?',
        en: 'Is the short supply chain the main reason for the higher price?',
      },
      {
        id: 'autumn-market-c4',
        speaker: 'partner',
        de: 'Teilweise. Entscheidend sind faire Löhne, kleine Mengen und der ökologische Anbau.',
        en: 'Partly. Fair wages, small quantities, and organic cultivation are decisive.',
      },
      {
        id: 'autumn-market-c5',
        speaker: 'you',
        de: 'Dann ist der Preis unter diesen Voraussetzungen nachvollziehbar.',
        en: 'Then the price is understandable under these conditions.',
      },
      {
        id: 'autumn-market-c6',
        speaker: 'partner',
        de: 'Genau. Außerdem verkaufen wir auch krummes Gemüse, statt es auszusortieren.',
        en: 'Exactly. We also sell misshapen vegetables instead of rejecting them.',
      },
      {
        id: 'autumn-market-c7',
        speaker: 'you',
        de: 'Wie lagere ich den Kürbis am besten, damit nichts verschwendet wird?',
        en: 'What is the best way to store the pumpkin so nothing is wasted?',
      },
      {
        id: 'autumn-market-c8',
        speaker: 'partner',
        de: 'Kühl und trocken hält er mehrere Wochen. Angeschnitten gehört er in den Kühlschrank.',
        en: 'Kept cool and dry, it lasts several weeks. Once cut, it belongs in the fridge.',
      },
    ],
    practiceQuestions: [
      {
        id: 'autumn-market-q1',
        kind: 'multiple-choice',
        prompt: 'Which question invites the vendor to explain provenance in detail?',
        options: [
          'Könnten Sie näher erläutern, woher dieses Gemüse stammt?',
          'Ist das billig?',
          'Geben Sie mir irgendetwas.',
        ],
        answerIndex: 0,
        explanation: 'It is polite, specific, and asks for more than a one-word answer.',
      },
      {
        id: 'autumn-market-q2',
        kind: 'fill-blank',
        prompt: 'Complete the phrase about distribution.',
        sentence: 'Eine kurze ___ kann Transportwege reduzieren.',
        answer: 'Lieferkette',
        alternatives: [],
        explanation: '„Die Lieferkette“ describes the route from producer to customer.',
      },
      {
        id: 'autumn-market-q3',
        kind: 'write-sentence',
        prompt: 'Politely ask why the price is justified.',
        mustInclude: ['Preis'],
        sample: 'Könnten Sie erläutern, wodurch sich dieser Preis rechtfertigt?',
        explanation:
          'This wording asks about value and production conditions without sounding confrontational.',
      },
    ],
    badge: {
      title: 'Marktprofi',
      emoji: '🌾',
      description: 'Discussed provenance, seasonality, and fair pricing at a local market.',
    },
  },
];

export const AUTUMN_MISSION_IDS = new Set(AUTUMN_MISSIONS.map((mission) => mission.id));
