import type { ConversationLine, Level, Mission, MissionAccent, MissionIcon } from '@/lib/types';

type VocabPair = readonly [de: string, en: string];
type DialogueLine = readonly [speaker: 'you' | 'partner', de: string, en: string];

interface ScenarioMissionInput {
  id: string;
  title: string;
  tagline: string;
  category: string;
  icon: MissionIcon;
  level: Level;
  minutes: number;
  accent: MissionAccent;
  where: string;
  reflectionFocus: string;
  realLifeSteps: string[];
  vocab: VocabPair[];
  dialogue: DialogueLine[];
  multipleChoice: {
    prompt: string;
    options: string[];
    answerIndex: number;
    explanation: string;
  };
  fillBlank: {
    prompt: string;
    sentence: string;
    answer: string;
    alternatives?: string[];
    explanation: string;
  };
  writeSentence: {
    prompt: string;
    mustInclude: string[];
    sample: string;
    explanation: string;
  };
  badge: Mission['badge'];
}

function createScenarioMission(input: ScenarioMissionInput): Mission {
  return {
    id: input.id,
    title: input.title,
    tagline: input.tagline,
    category: input.category,
    icon: input.icon,
    level: input.level,
    minutes: input.minutes,
    accent: input.accent,
    where: input.where,
    reflectionFocus: input.reflectionFocus,
    realLifeSteps: input.realLifeSteps,
    vocab: input.vocab.map(([de, en], index) => ({
      id: `${input.id}-v${index + 1}`,
      de,
      en,
      note: 'Say it aloud, then use it in the conversation practice.',
    })),
    conversationSimulation: input.dialogue.map<ConversationLine>(([speaker, de, en], index) => ({
      id: `${input.id}-c${index + 1}`,
      speaker,
      de,
      en,
    })),
    practiceQuestions: [
      { id: `${input.id}-q1`, kind: 'multiple-choice', ...input.multipleChoice },
      {
        id: `${input.id}-q2`,
        kind: 'fill-blank',
        alternatives: [],
        ...input.fillBlank,
      },
      { id: `${input.id}-q3`, kind: 'write-sentence', ...input.writeSentence },
    ],
    badge: input.badge,
  };
}

export const SCENARIO_MISSIONS: Mission[] = [
  createScenarioMission({
    id: 'casual-conversation-a1',
    title: 'Café small talk',
    tagline: 'Start an easy conversation over coffee.',
    category: 'Making friends',
    icon: 'users',
    level: 'beginner',
    minutes: 15,
    accent: 'sky',
    where: 'A relaxed café in your neighbourhood.',
    reflectionFocus: 'start a short café conversation',
    realLifeSteps: [
      'Choose a café at a quiet time.',
      'Ask whether a seat is free.',
      'Say that you are new in Hamburg.',
      'Ask one friendly question.',
      'End with a warm goodbye.',
    ],
    vocab: [
      ['das Café', 'café'],
      ['der Kaffee / der Tee', 'coffee / tea'],
      ['neu sein', 'to be new'],
      ['der Ort / die Stadt', 'place / city'],
      ['Wo kommst du her?', 'Where are you from?'],
      ['Wie geht es dir?', 'How are you?'],
      ['Das ist meine erste Woche.', 'This is my first week.'],
      ['Magst du Hamburg?', 'Do you like Hamburg?'],
    ],
    dialogue: [
      ['partner', 'Hallo! Der Platz ist noch frei, ja?', 'Hi! Is this seat still free?'],
      ['you', 'Ja, bitte! Setz dich hin.', 'Yes, please! Sit down.'],
      ['partner', 'Danke. Wie geht es dir? Ich bin Max.', "Thanks. How are you? I'm Max."],
      [
        'you',
        'Mir geht’s gut! Ich bin Sam. Ich bin neu hier in Hamburg.',
        "I'm good! I'm Sam. I'm new here in Hamburg.",
      ],
      ['partner', 'Wo kommst du her?', 'Where are you from?'],
      [
        'you',
        'Ich komme aus England. Ich bin hier seit zwei Wochen.',
        "I'm from England. I've been here for two weeks.",
      ],
      ['partner', 'Willkommen! Magst du Hamburg?', 'Welcome! Do you like Hamburg?'],
      ['you', 'Ja, sehr! Die Menschen sind nett.', 'Yes, very much! The people are nice.'],
    ],
    multipleChoice: {
      prompt: 'Wie lange ist Sam schon in Hamburg?',
      options: ['Eine Woche', 'Zwei Wochen', 'Einen Monat'],
      answerIndex: 1,
      explanation: 'Sam says „seit zwei Wochen“.',
    },
    fillBlank: {
      prompt: 'Complete the friendly answer.',
      sentence: 'Mir geht’s ___.',
      answer: 'gut',
      explanation: '„Mir geht’s gut“ is the standard short reply.',
    },
    writeSentence: {
      prompt: 'Write where you are from.',
      mustInclude: ['Ich komme aus'],
      sample: 'Ich komme aus England.',
      explanation: 'Use „Ich komme aus“ followed by your country or city.',
    },
    badge: {
      title: 'Café Starter',
      emoji: '☕',
      description: 'Started a friendly café conversation in German.',
    },
  }),
  createScenarioMission({
    id: 'running-club-first-run-a1-a2',
    title: 'First group run',
    tagline: 'Join a running group and ask about the route.',
    category: 'Making friends',
    icon: 'users',
    level: 'beginner',
    minutes: 20,
    accent: 'coral',
    where: 'A beginner-friendly Hamburg Lauftreff.',
    reflectionFocus: 'join a group activity and ask about the plan',
    realLifeSteps: [
      'Find a beginner-friendly Lauftreff.',
      'Introduce yourself as new.',
      'Ask how far the group will run.',
      'Check that the pace works for you.',
      'Talk to one runner after the session.',
    ],
    vocab: [
      ['der Lauftreff', 'running club / running meetup'],
      ['die Strecke', 'route / distance'],
      ['das Tempo', 'pace'],
      ['sich aufwärmen', 'to warm up'],
      ['die Kondition', 'fitness / stamina'],
      ['neu hier sein', 'to be new here'],
      ['Wie weit laufen wir?', 'How far are we running?'],
      ['Läufst du oft?', 'Do you run often?'],
    ],
    dialogue: [
      [
        'partner',
        'Hallo! Bist du neu hier beim Lauftreff?',
        'Hi! Are you new to the running club?',
      ],
      ['you', 'Ja, ich bin neu hier. Ich heiße Sam.', "Yes, I'm new here. I'm Sam."],
      [
        'partner',
        'Wir wärmen uns kurz auf, dann geht’s los.',
        'We warm up briefly, then we start.',
      ],
      ['you', 'Wie weit laufen wir heute?', 'How far are we running today?'],
      [
        'partner',
        'Die Strecke ist fünf Kilometer, ganz lockeres Tempo.',
        'The route is five kilometres at an easy pace.',
      ],
      ['you', 'Perfekt, das passt zu meiner Kondition.', 'Perfect, that suits my fitness level.'],
      ['partner', 'Läufst du oft?', 'Do you run often?'],
      ['you', 'Ja, zwei- oder dreimal pro Woche.', 'Yes, two or three times a week.'],
    ],
    multipleChoice: {
      prompt: 'Wie ist das Tempo heute?',
      options: ['Ganz locker', 'Sehr schnell', 'Es gibt kein Tempo'],
      answerIndex: 0,
      explanation: 'The runner describes it as „ganz lockeres Tempo“.',
    },
    fillBlank: {
      prompt: 'Introduce yourself at the club.',
      sentence: 'Ich bin ___ beim Lauftreff.',
      answer: 'neu hier',
      alternatives: ['neu'],
      explanation: '„Neu hier“ tells the group this is your first visit.',
    },
    writeSentence: {
      prompt: 'Write one line about joining a group activity.',
      mustInclude: ['Lauftreff'],
      sample: 'Heute gehe ich zum ersten Mal zum Lauftreff.',
      explanation: 'Name the activity and make the first visit clear.',
    },
    badge: {
      title: 'Mitläufer',
      emoji: '🏃',
      description: 'Joined a group activity and spoke German.',
    },
  }),
  createScenarioMission({
    id: 'doctor-first-visit-a2',
    title: 'First doctor visit',
    tagline: 'Check in and describe a simple symptom.',
    category: 'Everyday errands',
    icon: 'compass',
    level: 'beginner',
    minutes: 20,
    accent: 'sky',
    where: 'Your Hausarzt practice or a walk-in clinic.',
    reflectionFocus: 'check in and explain a symptom at the doctor',
    realLifeSteps: [
      'Bring your insurance card.',
      'State your appointment time at reception.',
      'Listen for the waiting-room instruction.',
      'Describe where it hurts and for how long.',
      'Ask what happens next.',
    ],
    vocab: [
      ['der Termin', 'appointment'],
      ['die Versicherungskarte', 'insurance card'],
      ['die Beschwerden', 'symptoms'],
      ['die Anmeldung', 'reception desk'],
      ['der Wartebereich', 'waiting room'],
      ['das Rezept', 'prescription'],
      ['Wo tut es weh?', 'Where does it hurt?'],
      ['Ich habe Kopfschmerzen.', 'I have a headache.'],
    ],
    dialogue: [
      ['partner', 'Guten Tag! Haben Sie einen Termin?', 'Hello! Do you have an appointment?'],
      [
        'you',
        'Ja, um zehn Uhr. Hier ist meine Versicherungskarte.',
        'Yes, at ten. Here is my insurance card.',
      ],
      ['partner', 'Bitte setzen Sie sich in den Wartebereich.', 'Please sit in the waiting room.'],
      ['partner', 'Guten Tag. Wo tut es weh?', 'Hello. Where does it hurt?'],
      ['you', 'Ich habe Kopfschmerzen seit zwei Tagen.', 'I have had a headache for two days.'],
      ['partner', 'Haben Sie noch andere Beschwerden?', 'Do you have any other symptoms?'],
      ['you', 'Nein, nur die Kopfschmerzen.', 'No, just the headache.'],
      ['partner', 'Gut, ich gebe Ihnen ein Rezept.', "Good, I'll give you a prescription."],
    ],
    multipleChoice: {
      prompt: 'Was fragt der Arzt zuerst?',
      options: ['Wo tut es weh?', 'Wie heißen Sie?', 'Wo wohnen Sie?'],
      answerIndex: 0,
      explanation: 'The doctor first asks where it hurts.',
    },
    fillBlank: {
      prompt: 'Describe the symptom.',
      sentence: 'Ich habe ___ seit zwei Tagen.',
      answer: 'Kopfschmerzen',
      explanation: 'Use the symptom directly after „Ich habe“.',
    },
    writeSentence: {
      prompt: 'Write one sentence about an appointment.',
      mustInclude: ['Termin'],
      sample: 'Ich habe morgen um zehn Uhr einen Termin.',
      explanation: 'Include the day or time to make the sentence useful.',
    },
    badge: {
      title: 'Praxis-Profi',
      emoji: '🩺',
      description: 'Handled a first doctor visit in German.',
    },
  }),
  createScenarioMission({
    id: 'bank-account-a2',
    title: 'Open a bank account',
    tagline: 'Ask about documents, forms, and fees.',
    category: 'Everyday errands',
    icon: 'compass',
    level: 'beginner',
    minutes: 25,
    accent: 'coral',
    where: 'A local bank branch with appointment service.',
    reflectionFocus: 'ask what you need to open a bank account',
    realLifeSteps: [
      'Book or confirm a branch appointment.',
      'Say you want to open an account.',
      'Show your passport and address proof.',
      'Ask about fees and cards.',
      'Confirm when the account becomes active.',
    ],
    vocab: [
      ['die Bank / das Konto', 'bank / account'],
      ['das Geld / die Geldbörse', 'money / wallet'],
      ['der Ausweis / der Pass', 'ID / passport'],
      ['das Formular', 'form'],
      ['die Gebühr', 'fee'],
      ['das Passbuch / die Karte', 'passbook / card'],
      ['Ich möchte ein Konto eröffnen.', 'I want to open an account.'],
      ['Welche Dokumente brauche ich?', 'What documents do I need?'],
    ],
    dialogue: [
      ['partner', 'Guten Tag! Wie kann ich helfen?', 'Hello! How can I help?'],
      ['you', 'Ich möchte ein Konto eröffnen.', 'I want to open an account.'],
      ['partner', 'Haben Sie einen Ausweis oder einen Pass?', 'Do you have an ID or passport?'],
      [
        'you',
        'Ich habe meinen Pass und einen Adressnachweis.',
        'I have my passport and proof of address.',
      ],
      ['partner', 'Bitte füllen Sie dieses Formular aus.', 'Please fill out this form.'],
      ['you', 'Gibt es Gebühren für das Konto?', 'Are there fees for the account?'],
      [
        'partner',
        'Das Girokonto ist kostenlos. Sie bekommen eine Karte.',
        'The current account is free. You receive a card.',
      ],
      ['you', 'Wann ist das Konto aktiv?', 'When is the account active?'],
    ],
    multipleChoice: {
      prompt: 'Welche Dokumente braucht man?',
      options: ['Nur den Pass', 'Pass und Adressnachweis', 'Nur einen Ausweis'],
      answerIndex: 1,
      explanation: 'The adviser asks for identification and proof of address.',
    },
    fillBlank: {
      prompt: 'Complete the sentence about costs.',
      sentence: 'Es gibt keine ___.',
      answer: 'Gebühren',
      explanation: '„Gebühren“ are account fees.',
    },
    writeSentence: {
      prompt: 'Write why you are at the bank.',
      mustInclude: ['Konto'],
      sample: 'Ich möchte bei dieser Bank ein Konto eröffnen.',
      explanation: 'State the task directly and politely.',
    },
    badge: {
      title: 'Konto-Klar',
      emoji: '💳',
      description: 'Asked the essential banking questions in German.',
    },
  }),
  createScenarioMission({
    id: 'forest-hiking-a2',
    title: 'A day in nature',
    tagline: 'Ask about a trail, the weather, and a break.',
    category: 'Making friends',
    icon: 'compass',
    level: 'beginner',
    minutes: 20,
    accent: 'magenta',
    where: 'A signed trail near Hamburg, with a friend or walking group.',
    reflectionFocus: 'ask practical questions during a group hike',
    realLifeSteps: [
      'Choose a signed beginner trail.',
      'Ask how far the walk is.',
      'Talk about the weather.',
      'Ask for a pause when you need one.',
      'Describe one thing you notice in nature.',
    ],
    vocab: [
      ['wandern / die Wanderung', 'to hike / hiking trip'],
      ['der Berg / der Hügel', 'mountain / hill'],
      ['der Weg / der Pfad', 'path / trail'],
      ['die Natur', 'nature'],
      ['das Wetter', 'weather'],
      ['die Pause', 'break'],
      ['Wie weit ist es bis zum Gipfel?', 'How far is it to the summit?'],
      ['Lass uns eine Pause machen.', "Let's take a break."],
    ],
    dialogue: [
      [
        'partner',
        'Willkommen zur Wanderung! Wir gehen zusammen in den Wald.',
        "Welcome to the hike! We're going into the forest.",
      ],
      ['you', 'Wie weit ist es bis zum Gipfel?', 'How far is it to the summit?'],
      [
        'partner',
        'Es sind nur fünf Kilometer. Der Weg ist einfach.',
        "It's only five kilometres. The trail is easy.",
      ],
      ['you', 'Und wie ist das Wetter heute?', "And how's the weather today?"],
      ['partner', 'Ein bisschen kühl, aber sonnig.', 'A little cool, but sunny.'],
      ['you', 'Wie lange brauchen wir?', 'How long will it take?'],
      [
        'partner',
        'Vielleicht zwei Stunden. Wir machen Pausen.',
        "Maybe two hours. We'll take breaks.",
      ],
      ['you', 'Lass uns eine Pause machen.', "Let's take a break."],
    ],
    multipleChoice: {
      prompt: 'Wie weit ist die Wanderung?',
      options: ['Drei Kilometer', 'Fünf Kilometer', 'Zehn Kilometer'],
      answerIndex: 1,
      explanation: 'The route is five kilometres.',
    },
    fillBlank: {
      prompt: 'Complete the description.',
      sentence: 'Im Herbst ist die Natur am ___.',
      answer: 'schönsten',
      explanation: '„Am schönsten“ is the superlative form.',
    },
    writeSentence: {
      prompt: 'Write one sentence about hiking.',
      mustInclude: ['Natur'],
      sample: 'Ich wandere gern in der Natur.',
      explanation: 'A short personal sentence is enough.',
    },
    badge: { title: 'Wald-Wanderer', emoji: '🥾', description: 'Used German on a walk in nature.' },
  }),
  createScenarioMission({
    id: 'auslanderbehorde-appointment-a2',
    title: 'Residence permit appointment',
    tagline: 'Handle documents and questions at the immigration office.',
    category: 'Everyday errands',
    icon: 'compass',
    level: 'intermediate',
    minutes: 25,
    accent: 'sky',
    where: 'Hamburg Amt für Migration or your district service centre.',
    reflectionFocus: 'handle a residence permit appointment',
    realLifeSteps: [
      'Check your appointment and document list.',
      'State your appointment time.',
      'Show your queue number.',
      'Explain what you want to renew.',
      'Confirm how you will receive the decision.',
    ],
    vocab: [
      ['der Aufenthaltstitel', 'residence permit'],
      ['die Anmeldebescheinigung', 'registration certificate'],
      ['der Reisepass', 'passport'],
      ['das Formular', 'form'],
      ['die Wartenummer', 'queue number'],
      ['der Sachbearbeiter / die Sachbearbeiterin', 'case worker'],
      ['Welche Unterlagen brauche ich?', 'Which documents do I need?'],
      ['Ich habe einen Termin um…', 'I have an appointment at…'],
    ],
    dialogue: [
      [
        'you',
        'Guten Tag, ich habe einen Termin um elf Uhr.',
        'Hello, I have an appointment at eleven.',
      ],
      ['partner', 'Ihre Wartenummer, bitte.', 'Your queue number, please.'],
      [
        'you',
        'Ich möchte meinen Aufenthaltstitel verlängern.',
        'I would like to extend my residence permit.',
      ],
      [
        'partner',
        'Haben Sie Ihren Reisepass und die Anmeldebescheinigung dabei?',
        'Do you have your passport and registration certificate?',
      ],
      [
        'you',
        'Ja, und ich habe das Formular schon ausgefüllt.',
        'Yes, and I already completed the form.',
      ],
      [
        'partner',
        'Welche Unterlagen haben Sie noch mitgebracht?',
        'Which other documents did you bring?',
      ],
      ['you', 'Einen Nachweis über meine Krankenversicherung.', 'Proof of my health insurance.'],
      [
        'partner',
        'Danke. Sie bekommen die Entscheidung per Post.',
        'Thank you. You will receive the decision by post.',
      ],
    ],
    multipleChoice: {
      prompt: 'Was fragt die Sachbearbeiterin zuerst?',
      options: ['Nach der Wartenummer', 'Nach dem Namen', 'Nach der Adresse'],
      answerIndex: 0,
      explanation: 'The case worker first asks for the queue number.',
    },
    fillBlank: {
      prompt: 'State what you want to renew.',
      sentence: 'Ich möchte meinen ___ verlängern.',
      answer: 'Aufenthaltstitel',
      explanation: '„Aufenthaltstitel“ is the formal word used at the office.',
    },
    writeSentence: {
      prompt: 'Write one sentence about your appointment.',
      mustInclude: ['Termin'],
      sample: 'Ich habe heute um elf Uhr einen Termin.',
      explanation: 'Include a clear time so staff can find the booking.',
    },
    badge: {
      title: 'Amt-Bereit',
      emoji: '📄',
      description: 'Handled a formal appointment in German.',
    },
  }),
  createScenarioMission({
    id: 'apartment-viewing-b1',
    title: 'Apartment viewing',
    tagline: 'Ask about rent, costs, and move-in dates.',
    category: 'Everyday errands',
    icon: 'compass',
    level: 'intermediate',
    minutes: 25,
    accent: 'coral',
    where: 'An apartment viewing in Hamburg.',
    reflectionFocus: 'ask detailed questions at an apartment viewing',
    realLifeSteps: [
      'Confirm the viewing address and time.',
      'Ask the monthly rent.',
      'Ask what the additional costs include.',
      'Clarify the deposit and furnishing.',
      'Confirm the earliest move-in date.',
    ],
    vocab: [
      ['die Wohnung', 'apartment'],
      ['die Miete', 'rent'],
      ['der Makler', 'real estate agent'],
      ['die Nebenkosten', 'utilities / additional costs'],
      ['die Kaution', 'security deposit'],
      ['möbliert / unmöbliert', 'furnished / unfurnished'],
      ['Wann können Sie einziehen?', 'When can you move in?'],
      ['Welche Bedingungen gelten für die Kaution?', 'What are the deposit terms?'],
    ],
    dialogue: [
      [
        'partner',
        'Das ist die Wohnung. Gefällt sie Ihnen?',
        'This is the apartment. Do you like it?',
      ],
      ['you', 'Ja. Wie hoch ist die Miete pro Monat?', 'Yes. How much is the monthly rent?'],
      [
        'partner',
        'Die Miete beträgt 1200 Euro, die Nebenkosten 150 Euro.',
        'The rent is 1200 euros and utilities are 150.',
      ],
      ['you', 'Was sind die Bedingungen für die Kaution?', 'What are the deposit terms?'],
      ['partner', 'Die Kaution ist drei Monatsmieten.', "The deposit is three months' rent."],
      [
        'you',
        'Wann könnte ich einziehen? Ist die Wohnung möbliert?',
        'When could I move in? Is it furnished?',
      ],
      [
        'partner',
        'Ab nächstem Monat. Die Wohnung ist unmöbliert.',
        'From next month. The apartment is unfurnished.',
      ],
      ['you', 'Kann ich die anderen Zimmer sehen?', 'Can I see the other rooms?'],
    ],
    multipleChoice: {
      prompt: 'Wie hoch ist die Kaution?',
      options: ['1200 Euro', '1350 Euro', '3600 Euro'],
      answerIndex: 2,
      explanation: 'Three months at 1200 euros equals 3600 euros.',
    },
    fillBlank: {
      prompt: 'Complete the rent statement.',
      sentence: 'Die Miete beträgt ___ Euro pro Monat.',
      answer: '1200',
      alternatives: ['1.200'],
      explanation: '„Beträgt“ is common in formal price statements.',
    },
    writeSentence: {
      prompt: 'Write one question about an apartment.',
      mustInclude: ['Wohnung'],
      sample: 'Ab wann ist die Wohnung verfügbar?',
      explanation: 'Ask about one detail you genuinely need.',
    },
    badge: {
      title: 'Wohnungs-Scout',
      emoji: '🏠',
      description: 'Asked the key questions at an apartment viewing.',
    },
  }),
  createScenarioMission({
    id: 'apartment-emergency-b1',
    title: 'Apartment emergency',
    tagline: 'Report urgent damage clearly to your landlord.',
    category: 'Everyday errands',
    icon: 'compass',
    level: 'intermediate',
    minutes: 20,
    accent: 'magenta',
    where: 'At home, by phone with your landlord or building manager.',
    reflectionFocus: 'report an urgent apartment problem',
    realLifeSteps: [
      'Move away from immediate danger.',
      'Call the landlord or emergency contact.',
      'State your name and apartment number.',
      'Describe the damage and urgency.',
      'Confirm who is coming and when.',
    ],
    vocab: [
      ['das Problem / der Schaden', 'problem / damage'],
      ['die Heizung', 'heating'],
      ['das Rohr / das Wasser', 'pipe / water'],
      ['lecken / tropfen', 'to leak / drip'],
      ['der Vermieter', 'landlord'],
      ['sofort / dringend', 'immediately / urgent'],
      ['Das Wasser kommt aus der Decke!', 'Water is coming from the ceiling!'],
      ['Es ist ein Notfall.', 'It is an emergency.'],
    ],
    dialogue: [
      [
        'you',
        'Ich bin Sam aus der Wohnung 3B. Es ist ein Notfall.',
        "I'm Sam from apartment 3B. It's an emergency.",
      ],
      ['partner', 'Was ist das Problem?', 'What is the problem?'],
      [
        'you',
        'Das Wasser tropft von der Decke und es wird schlimmer.',
        'Water is dripping from the ceiling and getting worse.',
      ],
      ['partner', 'Haben Sie das Wasser ausgemacht?', 'Have you turned off the water?'],
      [
        'you',
        'Ich weiß nicht, wo der Hauptschalter ist. Können Sie sofort kommen?',
        "I don't know where the main switch is. Can you come immediately?",
      ],
      ['partner', 'Ich rufe direkt den Handwerker an.', "I'll call the technician immediately."],
      ['you', 'Wie lange braucht der Handwerker?', 'How long will the technician take?'],
      [
        'partner',
        'Er kommt in einer Stunde. Bleiben Sie zu Hause.',
        'He will arrive in one hour. Stay at home.',
      ],
    ],
    multipleChoice: {
      prompt: 'Welches Problem hat die Wohnung?',
      options: ['Das Fenster ist kaputt', 'Wasser tropft von der Decke', 'Das Licht ist aus'],
      answerIndex: 1,
      explanation: 'The caller reports water dripping from the ceiling.',
    },
    fillBlank: {
      prompt: 'Make the urgency clear.',
      sentence: 'Es ist ein ___.',
      answer: 'Notfall',
      explanation: '„Notfall“ signals that immediate action is needed.',
    },
    writeSentence: {
      prompt: 'Describe urgent damage.',
      mustInclude: ['Schaden'],
      sample: 'Der Schaden wird größer und ich brauche sofort Hilfe.',
      explanation: 'Name the damage and the urgency clearly.',
    },
    badge: {
      title: 'Notfall-Klar',
      emoji: '🔧',
      description: 'Reported an urgent housing problem clearly.',
    },
  }),
  createScenarioMission({
    id: 'dating-first-date-b1',
    title: 'First date conversation',
    tagline: 'Ask thoughtful questions and share your plans.',
    category: 'Making friends',
    icon: 'users',
    level: 'intermediate',
    minutes: 20,
    accent: 'sky',
    where: 'A relaxed café, bar, or walk by the Alster.',
    reflectionFocus: 'have a personal conversation with someone new',
    realLifeSteps: [
      'Choose a place where conversation is easy.',
      'Say honestly if you feel nervous.',
      'Ask about hobbies and free time.',
      'Share one dream or plan.',
      'Ask one genuine follow-up question.',
    ],
    vocab: [
      ['das Date / die Verabredung', 'date / appointment'],
      ['nervös sein', 'to be nervous'],
      ['die Frage', 'question'],
      ['interessant / langweilig', 'interesting / boring'],
      ['das Hobby', 'hobby'],
      ['der Traum / der Plan', 'dream / plan'],
      ['Was machst du gerne in deiner Freizeit?', 'What do you like to do in your free time?'],
      ['Ich finde dich sehr interessant.', 'I find you very interesting.'],
    ],
    dialogue: [
      [
        'you',
        'Schön, dich wiederzusehen. Ich bin ein bisschen nervös!',
        "Good to see you again. I'm a little nervous!",
      ],
      ['partner', 'Ich auch! Was magst du trinken?', 'Me too! What would you like to drink?'],
      [
        'you',
        'Was machst du gerne in deiner Freizeit?',
        'What do you like doing in your free time?',
      ],
      [
        'partner',
        'Ich liebe Klettern. Das ist mein großes Hobby.',
        'I love climbing. It is my big hobby.',
      ],
      ['partner', 'Was ist dein großer Traum?', 'What is your big dream?'],
      [
        'you',
        'Mein Traum ist, eines Tages in Japan zu arbeiten.',
        'My dream is to work in Japan one day.',
      ],
      ['partner', 'Das ist ein cooler Plan!', 'That is a cool plan!'],
      [
        'you',
        'Ich möchte dich auch besser kennenlernen.',
        'I would also like to get to know you better.',
      ],
    ],
    multipleChoice: {
      prompt: 'Was ist das Hobby des Dates?',
      options: ['Schwimmen', 'Klettern', 'Tennis'],
      answerIndex: 1,
      explanation: 'The date says „Ich liebe Klettern“.',
    },
    fillBlank: {
      prompt: 'Describe how you feel.',
      sentence: 'Ich bin ein bisschen ___.',
      answer: 'nervös',
      explanation: '„Nervös“ is a natural, honest way to say how you feel.',
    },
    writeSentence: {
      prompt: 'Write what you find interesting.',
      mustInclude: ['interessant'],
      sample: 'Ich finde deine Reisen sehr interessant.',
      explanation: 'Connect „interessant“ to something the other person shared.',
    },
    badge: {
      title: 'Gesprächsfunke',
      emoji: '💬',
      description: 'Kept a personal conversation moving in German.',
    },
  }),
  createScenarioMission({
    id: 'expat-meetup-b1',
    title: 'Expat networking event',
    tagline: 'Introduce yourself and exchange Hamburg stories.',
    category: 'Making friends',
    icon: 'users',
    level: 'intermediate',
    minutes: 25,
    accent: 'coral',
    where: 'An international meetup or community event in Hamburg.',
    reflectionFocus: 'introduce yourself at a networking event',
    realLifeSteps: [
      'Attend an open meetup.',
      'Introduce yourself to one person.',
      'Ask what brought them to Hamburg.',
      'Share your work or reason for moving.',
      'Ask for one local tip.',
    ],
    vocab: [
      ['das Netzwerk / die Gruppe', 'network / group'],
      ['der Austausch', 'exchange / conversation'],
      ['auswandern / die Ausländerin', 'to emigrate / foreigner'],
      ['der Grund', 'reason / purpose'],
      ['der Beruf / arbeiten', 'profession / to work'],
      ['die Erfahrung', 'experience'],
      ['Was brachte dich nach Hamburg?', 'What brought you to Hamburg?'],
      ['Wie lange bist du schon hier?', 'How long have you been here?'],
    ],
    dialogue: [
      ['partner', 'Willkommen zum Austausch! Ich bin Julia.', "Welcome to the meetup! I'm Julia."],
      ['you', 'Danke! Das ist mein erstes Mal hier.', "Thanks! It's my first time here."],
      ['partner', 'Was brachte dich nach Hamburg?', 'What brought you to Hamburg?'],
      ['you', 'Ich bin für die Arbeit hierher gekommen.', 'I came here for work.'],
      ['partner', 'Was ist dein Beruf?', 'What is your profession?'],
      ['you', 'Ich arbeite in der IT-Entwicklung.', 'I work in IT development.'],
      ['you', 'Wie lange bist du schon hier?', 'How long have you been here?'],
      [
        'partner',
        'Zwei Jahre. Der Austausch ist wichtig — du bist nicht allein!',
        'Two years. The exchange is important — you are not alone!',
      ],
    ],
    multipleChoice: {
      prompt: 'Was ist Sams Beruf?',
      options: ['Arzt', 'IT-Entwicklung', 'Lehrer'],
      answerIndex: 1,
      explanation: 'Sam says they work in IT development.',
    },
    fillBlank: {
      prompt: 'Complete the encouragement.',
      sentence: 'Der Austausch ist ___.',
      answer: 'wichtig',
      explanation: 'The speaker says the exchange is important.',
    },
    writeSentence: {
      prompt: 'Write why you moved to Hamburg.',
      mustInclude: ['Grund'],
      sample: 'Der Grund für meinen Umzug war die Arbeit.',
      explanation: 'Use „der Grund“ to explain your reason.',
    },
    badge: { title: 'Netzwerker', emoji: '🤝', description: 'Made a new connection at a meetup.' },
  }),
  createScenarioMission({
    id: 'furniture-shopping-b1',
    title: 'Furniture shopping',
    tagline: 'Compare size, price, and style with a friend.',
    category: 'Everyday errands',
    icon: 'compass',
    level: 'intermediate',
    minutes: 20,
    accent: 'magenta',
    where: 'A furniture store or second-hand shop in Hamburg.',
    reflectionFocus: 'compare furniture and make a choice in German',
    realLifeSteps: [
      'Measure your room before leaving.',
      'Ask whether an item will fit.',
      'Check the dimensions and price.',
      'Compare practical and visual details.',
      'Confirm transport or delivery.',
    ],
    vocab: [
      ['das Möbel / der Schrank', 'furniture / cabinet'],
      ['der Platz / der Raum', 'space / room'],
      ['das Regal', 'shelf'],
      ['praktisch / schön', 'practical / beautiful'],
      ['passen / zusammenpassen', 'to fit / match'],
      ['der Preis', 'price'],
      ['Passt das in dein Zimmer?', 'Will that fit in your room?'],
      ['Das passt perfekt zu deiner Einrichtung!', 'That matches your interior perfectly!'],
    ],
    dialogue: [
      ['partner', 'Dieser Schrank ist sehr praktisch.', 'This cabinet is very practical.'],
      [
        'you',
        'Passt das in mein Zimmer? Mein Raum ist nicht groß.',
        'Will that fit in my room? My room is not large.',
      ],
      [
        'partner',
        'Der Schrank ist zwei Meter breit. Das sollte passen.',
        'The cabinet is two metres wide. It should fit.',
      ],
      ['you', 'Und wie viel kostet das?', 'And how much does it cost?'],
      [
        'partner',
        '199 Euro. Dieses Regal passt perfekt zu deiner Einrichtung.',
        '199 euros. This shelf matches your interior perfectly.',
      ],
      ['you', 'Das Design ist modern. Das gefällt mir.', 'The design is modern. I like it.'],
      [
        'partner',
        'Am Wochenende können wir es zusammen aufbauen.',
        'We can assemble it together at the weekend.',
      ],
      [
        'you',
        'Perfekt! Dann wird die Wohnung schön und praktisch.',
        'Perfect! Then the apartment will be beautiful and practical.',
      ],
    ],
    multipleChoice: {
      prompt: 'Wie breit ist der Schrank?',
      options: ['Ein Meter', 'Eineinhalb Meter', 'Zwei Meter'],
      answerIndex: 2,
      explanation: 'The cabinet is two metres wide.',
    },
    fillBlank: {
      prompt: 'Complete the price.',
      sentence: 'Der Schrank kostet ___ Euro.',
      answer: '199',
      explanation: 'The price given in the conversation is 199 euros.',
    },
    writeSentence: {
      prompt: 'Write about furnishing your home.',
      mustInclude: ['Einrichtung'],
      sample: 'Das Regal passt gut zu meiner Einrichtung.',
      explanation: 'Use „passen zu“ to describe a match.',
    },
    badge: {
      title: 'Einrichtungs-Profi',
      emoji: '🪑',
      description: 'Compared furniture and made a choice in German.',
    },
  }),
  createScenarioMission({
    id: 'inviting-someone-over-b1',
    title: 'Host at home',
    tagline: 'Make an invitation and plan food safely.',
    category: 'Making friends',
    icon: 'users',
    level: 'intermediate',
    minutes: 20,
    accent: 'sky',
    where: 'Your home, while inviting a friend by message or in person.',
    reflectionFocus: 'invite someone over and plan the meal',
    realLifeSteps: [
      'Choose a clear day and time.',
      'Invite one person directly.',
      'Say what you plan to cook.',
      'Ask about allergies or dietary needs.',
      'Confirm what they should bring.',
    ],
    vocab: [
      ['einladen / die Einladung', 'to invite / invitation'],
      ['das Essen / kochen', 'food / to cook'],
      ['die Allergie', 'allergy'],
      ['die Vorspeise / der Hauptgang', 'appetizer / main course'],
      ['gemütlich', 'cozy / comfortable'],
      ['um … Uhr', 'at … o’clock'],
      [
        'Möchtest du Freitag zu mir nach Hause kommen?',
        'Would you like to come to my place on Friday?',
      ],
      ['Ich koche gerne für dich.', 'I like to cook for you.'],
    ],
    dialogue: [
      [
        'you',
        'Möchtest du Freitag zu mir nach Hause kommen?',
        'Would you like to come to my place on Friday?',
      ],
      ['partner', 'Das klingt wunderbar! Um wie viel Uhr?', 'That sounds wonderful! What time?'],
      ['you', 'Um 19 Uhr. Ich koche gerne für dich.', 'At 7 p.m. I like to cook for you.'],
      [
        'partner',
        'Ich bringe Wein mit. Ich habe eine Allergie gegen Nüsse.',
        "I'll bring wine. I have a nut allergy.",
      ],
      [
        'you',
        'Keine Sorge! Meine Pasta-Soße hat keine Nüsse.',
        'No problem! My pasta sauce has no nuts.',
      ],
      ['partner', 'Das klingt gemütlich und köstlich!', 'That sounds cosy and delicious!'],
      ['you', 'Du musst nur gute Laune mitbringen.', 'You only need to bring a good mood.'],
      [
        'partner',
        'Ich freue mich schon. Bis Freitag!',
        "I'm looking forward to it. See you Friday!",
      ],
    ],
    multipleChoice: {
      prompt: 'Was kocht die Person?',
      options: ['Fisch', 'Pasta', 'Fleisch'],
      answerIndex: 1,
      explanation: 'The host says they will make pasta.',
    },
    fillBlank: {
      prompt: 'Complete the allergy statement.',
      sentence: 'Ich habe eine Allergie gegen ___.',
      answer: 'Nüsse',
      explanation: 'The guest clearly names a nut allergy.',
    },
    writeSentence: {
      prompt: 'Write what you would cook for a friend.',
      mustInclude: ['kochen'],
      sample: 'Ich möchte für meinen Freund Pasta kochen.',
      explanation: 'Say who you are cooking for and what you will make.',
    },
    badge: {
      title: 'Gastgeber',
      emoji: '🍝',
      description: 'Planned a friendly, safe meal in German.',
    },
  }),
  createScenarioMission({
    id: 'job-interview-b1',
    title: 'First job interview',
    tagline: 'Present your experience and answer key questions.',
    category: 'Work and study',
    icon: 'users',
    level: 'intermediate',
    minutes: 25,
    accent: 'coral',
    where: 'A German-language interview online or at an office.',
    reflectionFocus: 'introduce your experience in a job interview',
    realLifeSteps: [
      'Review the role and company.',
      'Prepare a short self-introduction.',
      'Explain one relevant experience.',
      'Answer why you want the role.',
      'Ask one question about the team.',
    ],
    vocab: [
      ['die Stelle / der Job', 'job / position'],
      ['die Qualifikation', 'qualification'],
      ['die Erfahrung', 'experience'],
      ['der Lebenslauf', 'resume / CV'],
      ['das Anschreiben', 'cover letter'],
      ['sich vorstellen', 'to introduce oneself'],
      ['Weshalb möchten Sie bei uns arbeiten?', 'Why do you want to work for us?'],
      [
        'Wie würden Sie eine schwierige Situation lösen?',
        'How would you solve a difficult situation?',
      ],
    ],
    dialogue: [
      ['partner', 'Guten Tag. Bitte setzen Sie sich.', 'Hello. Please sit down.'],
      ['you', 'Vielen Dank für den Termin.', 'Thank you for the appointment.'],
      ['partner', 'Können Sie sich kurz vorstellen?', 'Can you briefly introduce yourself?'],
      [
        'you',
        'Ich habe fünf Jahre Erfahrung in IT-Support.',
        'I have five years of experience in IT support.',
      ],
      ['partner', 'Weshalb möchten Sie bei uns arbeiten?', 'Why do you want to work for us?'],
      [
        'you',
        'Die Stelle passt zu meinen Fähigkeiten und Zielen.',
        'The position fits my skills and goals.',
      ],
      [
        'partner',
        'Wie würden Sie eine schwierige Situation lösen?',
        'How would you solve a difficult situation?',
      ],
      [
        'you',
        'Ich würde zuhören und dann eine Lösung finden.',
        'I would listen and then find a solution.',
      ],
    ],
    multipleChoice: {
      prompt: 'Warum möchte Sam bei der Firma arbeiten?',
      options: [
        'Der Ruf ist gut und die Stelle passt',
        'Nur wegen des Gehalts',
        'Das Büro ist nah',
      ],
      answerIndex: 0,
      explanation: 'Sam connects the company and role to their goals.',
    },
    fillBlank: {
      prompt: 'Complete the experience statement.',
      sentence: 'Ich habe fünf Jahre ___ in IT-Support.',
      answer: 'Erfahrung',
      explanation: 'Use „Erfahrung in“ for a professional field.',
    },
    writeSentence: {
      prompt: 'Write about a role that interests you.',
      mustInclude: ['Stelle'],
      sample: 'Diese Stelle interessiert mich, weil ich gern im Team arbeite.',
      explanation: 'Give one concrete reason for your interest.',
    },
    badge: {
      title: 'Interview-Bereit',
      emoji: '💼',
      description: 'Presented professional experience in German.',
    },
  }),
  createScenarioMission({
    id: 'library-membership-b1',
    title: 'Join the library',
    tagline: 'Get a card, borrow a book, and find a group.',
    category: 'Everyday errands',
    icon: 'compass',
    level: 'intermediate',
    minutes: 20,
    accent: 'magenta',
    where: 'A Bücherhallen Hamburg branch.',
    reflectionFocus: 'get a library card and ask for a recommendation',
    realLifeSteps: [
      'Bring identification and address details.',
      'Ask for a library card.',
      'Request a book recommendation.',
      'Ask about the loan period.',
      'Find out when a reading group meets.',
    ],
    vocab: [
      ['die Bibliothek / Bücherei', 'library'],
      ['der Ausweis', 'library card / ID'],
      ['das Buch / der Roman', 'book / novel'],
      ['ausleihen / zurückgeben', 'to borrow / return'],
      ['der Autor / die Autorin', 'author'],
      ['die Lesegruppe', 'reading group'],
      ['Können Sie mir ein Buch über … empfehlen?', 'Can you recommend a book about …?'],
      ['Wie lange kann ich das Buch behalten?', 'How long can I keep the book?'],
    ],
    dialogue: [
      [
        'partner',
        'Ist das Ihr erstes Mal in unserer Bibliothek?',
        'Is this your first time in our library?',
      ],
      ['you', 'Ja. Ich möchte einen Ausweis beantragen.', 'Yes. I would like to apply for a card.'],
      [
        'partner',
        'Ich brauche Ihren Namen, Ihre Adresse und einen gültigen Ausweis.',
        'I need your name, address, and valid ID.',
      ],
      [
        'you',
        'Können Sie mir ein Buch über Hamburg empfehlen?',
        'Can you recommend a book about Hamburg?',
      ],
      ['partner', 'Ja, ich habe einen guten Roman für Sie.', 'Yes, I have a good novel for you.'],
      ['you', 'Wie lange kann ich das Buch behalten?', 'How long can I keep the book?'],
      ['partner', 'Sie können es vier Wochen ausleihen.', 'You can borrow it for four weeks.'],
      ['you', 'Gibt es auch eine Lesegruppe?', 'Is there also a reading group?'],
    ],
    multipleChoice: {
      prompt: 'Wie lange kann man ein Buch ausleihen?',
      options: ['Zwei Wochen', 'Vier Wochen', 'Sechs Wochen'],
      answerIndex: 1,
      explanation: 'The standard loan in this conversation is four weeks.',
    },
    fillBlank: {
      prompt: 'Complete the membership detail.',
      sentence: 'Die Mitgliedschaft ist ___.',
      answer: 'kostenlos',
      explanation: '„Kostenlos“ means there is no fee.',
    },
    writeSentence: {
      prompt: 'Write about an author you want to read.',
      mustInclude: ['Autor'],
      sample: 'Ich möchte einen Roman von einem deutschen Autor lesen.',
      explanation: 'Use „von“ to connect a book and its author.',
    },
    badge: {
      title: 'Bücherfreund',
      emoji: '📚',
      description: 'Joined a library and asked for a book in German.',
    },
  }),
  createScenarioMission({
    id: 'mushroom-foraging-b1',
    title: 'Mushroom foraging walk',
    tagline: 'Talk about nature while keeping safety first.',
    category: 'Making friends',
    icon: 'compass',
    level: 'intermediate',
    minutes: 20,
    accent: 'sky',
    where: 'A guided foraging walk with a qualified local expert.',
    reflectionFocus: 'ask safety questions on a guided nature walk',
    realLifeSteps: [
      'Only join a qualified guided walk.',
      'Bring a basket and suitable clothing.',
      'Ask before touching or collecting anything.',
      'Repeat the safety rule aloud.',
      'Leave every unidentified mushroom in place.',
    ],
    vocab: [
      ['der Pilz / die Pilze', 'mushroom / mushrooms'],
      ['der Wald', 'forest'],
      ['der Korb', 'basket'],
      ['giftig / essbar', 'poisonous / edible'],
      ['sammeln / pflücken', 'to collect / pick'],
      ['der Herbst', 'autumn / fall'],
      ['Dieser Pilz ist essbar, ja?', 'This mushroom is edible, yes?'],
      ['Wir sollten nur die bekannten Pilze nehmen.', 'We should only take mushrooms we know.'],
    ],
    dialogue: [
      [
        'partner',
        'Heute gehen wir Pilze sammeln im Wald. Du brauchst einen Korb.',
        'Today we are mushroom foraging in the forest. You need a basket.',
      ],
      ['you', 'Dieser Pilz ist essbar, ja?', 'This mushroom is edible, right?'],
      [
        'partner',
        'Nein, das ist ein Fliegenpilz — sehr giftig!',
        'No, that is a fly agaric — very poisonous!',
      ],
      ['you', 'Wie viele Pilze sollen wir pflücken?', 'How many mushrooms should we pick?'],
      [
        'partner',
        'Wir sollten nur die bekannten Pilze nehmen.',
        'We should only take mushrooms we know.',
      ],
      [
        'you',
        'Das ist wichtig. Der Wald ist schön im Herbst.',
        'That is important. The forest is beautiful in autumn.',
      ],
      ['partner', 'Ja, aber Sicherheit kommt zuerst.', 'Yes, but safety comes first.'],
      ['you', 'Unbekannte Pilze lasse ich stehen.', 'I leave unknown mushrooms alone.'],
    ],
    multipleChoice: {
      prompt: 'Welcher Pilz ist giftig?',
      options: ['Champignon', 'Fliegenpilz', 'Pfifferling'],
      answerIndex: 1,
      explanation: 'The guide identifies the fly agaric as poisonous.',
    },
    fillBlank: {
      prompt: 'Complete the location.',
      sentence: 'Im Herbst gehen viele Menschen in den ___.',
      answer: 'Wald',
      explanation: '„In den Wald“ uses the accusative after movement.',
    },
    writeSentence: {
      prompt: 'Write the safety rule.',
      mustInclude: ['Wald'],
      sample: 'Im Wald sammle ich nur Pilze mit einer Fachperson.',
      explanation: 'Never rely on language practice to identify edible mushrooms.',
    },
    badge: {
      title: 'Wald-Wach',
      emoji: '🍄',
      description: 'Asked clear safety questions on a guided walk.',
    },
  }),
  createScenarioMission({
    id: 'public-transport-b1',
    title: 'Buy a transport ticket',
    tagline: 'Ask about fares, routes, and where to get off.',
    category: 'Getting around',
    icon: 'compass',
    level: 'intermediate',
    minutes: 20,
    accent: 'coral',
    where: 'An HVV service point or staffed station.',
    reflectionFocus: 'plan a public transport journey in German',
    realLifeSteps: [
      'Choose a real destination.',
      'Ask which ticket you need.',
      'Confirm the price and journey time.',
      'Ask whether you must change.',
      'Confirm your final stop.',
    ],
    vocab: [
      ['die Fahrkarte / das Ticket', 'ticket'],
      ['die Haltestelle', 'stop / station'],
      ['der Fahrkartenautomat', 'ticket machine'],
      ['die Linie', 'line / route'],
      ['das Umsteigen', 'transfer / changing trains'],
      ['der Fahrplan', 'timetable / schedule'],
      ['Wie lange dauert die Fahrt?', 'How long does the journey take?'],
      ['Wo muss ich aussteigen?', 'Where do I need to get off?'],
    ],
    dialogue: [
      ['partner', 'Guten Tag! Womit kann ich Ihnen helfen?', 'Hello! How can I help you?'],
      [
        'you',
        'Ich möchte ein Ticket nach Eidelstedt kaufen.',
        'I would like to buy a ticket to Eidelstedt.',
      ],
      ['partner', 'Das Einzelticket kostet 3,10 Euro.', 'The single ticket costs 3.10 euros.'],
      ['you', 'Wie lange dauert die Fahrt?', 'How long does the journey take?'],
      [
        'partner',
        'Etwa 25 Minuten. Sie müssen nicht umsteigen.',
        'About 25 minutes. You do not need to change.',
      ],
      ['you', 'Wo muss ich aussteigen?', 'Where do I need to get off?'],
      [
        'partner',
        'An der Haltestelle Eidelstedt. Der Fahrplan hängt hier.',
        'At Eidelstedt stop. The timetable is here.',
      ],
      ['you', 'Danke für die Informationen!', 'Thank you for the information!'],
    ],
    multipleChoice: {
      prompt: 'Wie lange dauert die Fahrt?',
      options: ['15 Minuten', '25 Minuten', '35 Minuten'],
      answerIndex: 1,
      explanation: 'The journey takes about 25 minutes.',
    },
    fillBlank: {
      prompt: 'Complete the ticket price.',
      sentence: 'Das Einzelticket kostet ___ Euro.',
      answer: '3,10',
      alternatives: ['3.10'],
      explanation: 'German prices use a decimal comma.',
    },
    writeSentence: {
      prompt: 'Write about a Hamburg line you take.',
      mustInclude: ['Linie'],
      sample: 'Ich nehme die Linie U3 bis zur nächsten Haltestelle.',
      explanation: 'Name the line and destination.',
    },
    badge: {
      title: 'HVV-Helfer',
      emoji: '🚇',
      description: 'Planned a Hamburg journey in German.',
    },
  }),
  createScenarioMission({
    id: 'restaurant-reservation-b1',
    title: 'Restaurant reservation',
    tagline: 'Reserve a table and explain dietary needs.',
    category: 'Everyday errands',
    icon: 'utensils',
    level: 'intermediate',
    minutes: 20,
    accent: 'magenta',
    where: 'A Hamburg restaurant by phone or in person.',
    reflectionFocus: 'reserve a table and ask about the menu',
    realLifeSteps: [
      'Choose a restaurant and time.',
      'Reserve for a specific number of people.',
      'Give your name clearly.',
      'Ask about a specialty or vegetarian option.',
      'State any allergy directly.',
    ],
    vocab: [
      ['der Tisch', 'table'],
      ['die Reservierung / der Platz', 'reservation / place'],
      ['das Menü / die Speisekarte', 'menu'],
      ['die Spezialität', 'specialty dish'],
      ['die Zutat', 'ingredient'],
      ['vegetarisch / vegan', 'vegetarian / vegan'],
      ['Haben Sie noch einen Tisch für heute Abend?', 'Do you have a table for tonight?'],
      ['Ich bin allergisch gegen …', 'I am allergic to …'],
    ],
    dialogue: [
      [
        'partner',
        'Guten Abend! Haben Sie eine Reservierung?',
        'Good evening! Do you have a reservation?',
      ],
      [
        'you',
        'Ja, unter dem Namen Sam. Für zwei Personen um 19 Uhr.',
        'Yes, under Sam. For two people at 7 p.m.',
      ],
      ['partner', 'Hier ist Ihr Tisch.', 'Here is your table.'],
      ['you', 'Können Sie uns die Speisekarte bringen?', 'Can you bring us the menu?'],
      [
        'partner',
        'Selbstverständlich. Was möchten Sie trinken?',
        'Of course. What would you like to drink?',
      ],
      ['you', 'Was ist die Spezialität des Hauses?', 'What is the house speciality?'],
      ['partner', 'Unsere Spezialität ist der Fisch.', 'Our speciality is fish.'],
      ['you', 'Haben Sie auch vegetarische Optionen?', 'Do you also have vegetarian options?'],
    ],
    multipleChoice: {
      prompt: 'Was ist die Spezialität?',
      options: ['Fisch', 'Fleisch', 'Pasta'],
      answerIndex: 0,
      explanation: 'The server says the house speciality is fish.',
    },
    fillBlank: {
      prompt: 'Complete the reservation request.',
      sentence: 'Ich möchte einen Tisch für zwei Personen ___.',
      answer: 'reservieren',
      explanation: '„Einen Tisch reservieren“ is the standard phrase.',
    },
    writeSentence: {
      prompt: 'Write a reservation request.',
      mustInclude: ['Reservierung'],
      sample: 'Ich möchte eine Reservierung für Freitag um 19 Uhr machen.',
      explanation: 'Include the day, time, and group size.',
    },
    badge: {
      title: 'Tisch-Sicher',
      emoji: '🍽️',
      description: 'Reserved a table and asked about food in German.',
    },
  }),
  createScenarioMission({
    id: 'team-meeting-b1',
    title: 'Work team meeting',
    tagline: 'Ask for clarification and discuss a problem.',
    category: 'Work and study',
    icon: 'users',
    level: 'intermediate',
    minutes: 25,
    accent: 'sky',
    where: 'A team meeting at work or in a practice group.',
    reflectionFocus: 'ask for clarification in a work meeting',
    realLifeSteps: [
      'Read the meeting topic beforehand.',
      'Listen for the project status.',
      'Ask for clarification once.',
      'Restate what you understood.',
      'Volunteer for one clear next step.',
    ],
    vocab: [
      ['das Projekt / die Deadline', 'project / deadline'],
      ['der Fortschritt', 'progress'],
      ['das Hindernis / das Problem', 'obstacle / problem'],
      ['der Kollege / die Kollegin', 'colleague'],
      ['besprechen / diskutieren', 'to discuss / debate'],
      ['die Entscheidung', 'decision'],
      ['Können Sie das noch einmal erklären?', 'Can you explain that again?'],
      [
        'Ich bin mir nicht sicher, ob ich das verstanden habe.',
        'I am not sure whether I understood that.',
      ],
    ],
    dialogue: [
      [
        'partner',
        'Heute besprechen wir den Stand des Projekts.',
        'Today we discuss the project status.',
      ],
      [
        'partner',
        'Die Website ist 70 Prozent fertig, aber der Server ist langsam.',
        'The website is 70 percent complete, but the server is slow.',
      ],
      ['you', 'Können Sie das noch einmal erklären?', 'Can you explain that again?'],
      [
        'partner',
        'Der Code braucht länger, um die Daten zu laden.',
        'The code takes longer to load the data.',
      ],
      [
        'partner',
        'Wir haben noch zwei Wochen bis zur Deadline.',
        'We have two weeks until the deadline.',
      ],
      [
        'you',
        'Ich bin mir nicht sicher, ob ich das verstanden habe.',
        'I am not sure whether I understood that.',
      ],
      [
        'partner',
        'Wir müssen nur einen Teil des Codes ändern.',
        'We only need to change part of the code.',
      ],
      ['you', 'Gerne. Wann können wir anfangen?', 'Sure. When can we start?'],
    ],
    multipleChoice: {
      prompt: 'Wie lange ist es bis zur Deadline?',
      options: ['Eine Woche', 'Zwei Wochen', 'Ein Monat'],
      answerIndex: 1,
      explanation: 'The team has two weeks left.',
    },
    fillBlank: {
      prompt: 'Complete the progress update.',
      sentence: 'Das Projekt ist ___ fertig.',
      answer: '70 Prozent',
      alternatives: ['70%', 'siebzig Prozent'],
      explanation: 'Both the number and written form communicate the same progress.',
    },
    writeSentence: {
      prompt: 'Write about a project.',
      mustInclude: ['Projekt'],
      sample: 'In meinem Projekt arbeite ich mit zwei Kollegen zusammen.',
      explanation: 'Describe your role or current task.',
    },
    badge: {
      title: 'Meeting-Mutig',
      emoji: '📊',
      description: 'Asked for clarification in a German meeting.',
    },
  }),
  createScenarioMission({
    id: 'university-orientation-b2',
    title: 'University orientation',
    tagline: 'Ask about enrollment, requirements, and courses.',
    category: 'Work and study',
    icon: 'compass',
    level: 'advanced',
    minutes: 30,
    accent: 'coral',
    where: 'Universität Hamburg or another university advisory office.',
    reflectionFocus: 'ask detailed questions about university enrollment',
    realLifeSteps: [
      'Bring your program and document questions.',
      'Explain which degree interests you.',
      'Ask about the application process.',
      'Clarify prerequisites and language proof.',
      'Ask where international students get support.',
    ],
    vocab: [
      ['die Universität / die Hochschule', 'university'],
      ['die Immatrikulation', 'enrollment / registration'],
      ['das Seminar', 'seminar'],
      ['die Vorlesung', 'lecture'],
      ['das Studium', 'studies / degree program'],
      ['der Leistungsnachweis / der ECTS', 'credit points'],
      ['Wie funktioniert das Anmeldeverfahren?', 'How does the registration process work?'],
      [
        'Was sind die Voraussetzungen für diesen Studiengang?',
        'What are the prerequisites for this degree?',
      ],
    ],
    dialogue: [
      [
        'partner',
        'Willkommen an der Universität Hamburg. Wie kann ich helfen?',
        'Welcome to Hamburg University. How can I help?',
      ],
      [
        'you',
        'Ich möchte mich für einen Master-Studiengang immatrikulieren.',
        'I would like to enrol in a master’s programme.',
      ],
      [
        'you',
        'Können Sie mir das Anmeldeverfahren erklären?',
        'Can you explain the registration process?',
      ],
      [
        'partner',
        'Zuerst müssen Sie alle erforderlichen Unterlagen einreichen.',
        'First you must submit all required documents.',
      ],
      [
        'you',
        'Was sind die Voraussetzungen für diesen Studiengang?',
        'What are the prerequisites for this degree?',
      ],
      [
        'partner',
        'Sie brauchen auch ein Deutschtest-Zertifikat.',
        'You also need a German language certificate.',
      ],
      ['you', 'Gibt es Vorlesungen und Seminare?', 'Are there lectures and seminars?'],
      [
        'partner',
        'Ja, und Sie sammeln etwa 120 ECTS in zwei Jahren.',
        'Yes, and you earn about 120 ECTS in two years.',
      ],
    ],
    multipleChoice: {
      prompt: 'Was ist der genannte NC?',
      options: ['1,5', '2,0', '2,5'],
      answerIndex: 1,
      explanation: 'The adviser names an NC of 2.0.',
    },
    fillBlank: {
      prompt: 'Complete the course format.',
      sentence: 'Das Programm besteht aus Vorlesungen und ___.',
      answer: 'Seminaren',
      explanation: 'After „aus“ the plural dative is „Seminaren“.',
    },
    writeSentence: {
      prompt: 'Write about a degree that interests you.',
      mustInclude: ['Studiengang'],
      sample: 'Der Studiengang Informatik interessiert mich besonders.',
      explanation: 'Name the degree and your interest directly.',
    },
    badge: {
      title: 'Campus-Klar',
      emoji: '🎓',
      description: 'Asked detailed university questions in German.',
    },
  }),
  createScenarioMission({
    id: 'health-insurance-b2',
    title: 'Navigate health insurance',
    tagline: 'Compare coverage, premiums, and claim steps.',
    category: 'Everyday errands',
    icon: 'compass',
    level: 'advanced',
    minutes: 30,
    accent: 'magenta',
    where: 'A health-insurance service centre or advice call.',
    reflectionFocus: 'ask detailed questions about health insurance',
    realLifeSteps: [
      'Write down your employment and coverage needs.',
      'Ask about statutory and private options.',
      'Clarify premiums and included benefits.',
      'Ask about deductibles and referrals.',
      'Repeat back the next step before ending.',
    ],
    vocab: [
      ['die Krankenversicherung', 'health insurance'],
      ['der Versicherte', 'insured person'],
      ['der Beitrag', 'contribution / premium'],
      ['die Deckung', 'coverage'],
      ['der Selbstbehalt', 'deductible / out-of-pocket amount'],
      ['die Leistung', 'benefit / service'],
      [
        'Welche Leistungen sind in meinem Plan enthalten?',
        'What benefits are included in my plan?',
      ],
      ['Wie reiche ich einen Schadensfall ein?', 'How do I file a claim?'],
    ],
    dialogue: [
      [
        'partner',
        'Welche Art von Deckung suchen Sie?',
        'What type of coverage are you looking for?',
      ],
      [
        'you',
        'Was sind die Unterschiede zwischen gesetzlicher und privater Versicherung?',
        'What are the differences between statutory and private insurance?',
      ],
      [
        'partner',
        'Die gesetzliche Versicherung hat niedrigere Beiträge.',
        'Statutory insurance has lower premiums.',
      ],
      [
        'partner',
        'Die private Versicherung bietet mehr Leistungen, aber höhere Beiträge.',
        'Private insurance offers more benefits but higher premiums.',
      ],
      [
        'you',
        'Welche Leistungen sind in einem typischen Plan enthalten?',
        'Which benefits are included in a typical plan?',
      ],
      [
        'partner',
        'Arztbesuche, Medikamente und teilweise Zahnbehandlung.',
        'Doctor visits, medication, and some dental treatment.',
      ],
      ['you', 'Wie reiche ich einen Schadensfall ein?', 'How do I file a claim?'],
      [
        'partner',
        'Meist zeigen Sie einfach Ihre Versicherungskarte.',
        'Usually you simply show your insurance card.',
      ],
    ],
    multipleChoice: {
      prompt: 'Was ist ein typischer Selbstbehalt?',
      options: ['50 bis 100 Euro', '0 bis 300 Euro', '500 bis 1000 Euro'],
      answerIndex: 1,
      explanation: 'The adviser gives a typical range of zero to 300 euros.',
    },
    fillBlank: {
      prompt: 'Complete the comparison.',
      sentence: 'Die private Versicherung hat höhere ___.',
      answer: 'Beiträge',
      explanation: '„Beiträge“ are the recurring insurance premiums.',
    },
    writeSentence: {
      prompt: 'Write why insurance matters.',
      mustInclude: ['Krankenversicherung'],
      sample: 'Eine Krankenversicherung ist für Arztbesuche und Medikamente wichtig.',
      explanation: 'Connect the insurance to a practical benefit.',
    },
    badge: {
      title: 'Versicherungs-Klar',
      emoji: '🛡️',
      description: 'Compared health-insurance options in German.',
    },
  }),
];
