import type { Mission } from '@/lib/types';

export const makeLifeHappen: Mission = {
  id: 'make-life-happen',
  title: 'Make life happen',
  tagline: 'Order lunch, ask a question, and do the practical stuff in German.',
  category: 'Everyday errands',
  icon: 'utensils',
  level: 'intermediate',
  minutes: 20,
  accent: 'coral',
  where: 'A bakery, Imbiss or lunch counter — pick a quiet hour, not the 12:30 rush.',
  reflectionFocus: 'order and pay in German',
  realLifeSteps: [
    'Choose a counter with a short queue so nobody is rushing you.',
    'Order with „Ich hätte gern …, bitte.“',
    'Answer the takeaway question: „Zum Mitnehmen, bitte.“',
    'Ask one extra question — a recommendation, or something vegetarian.',
    'Pay in German: „Mit Karte, bitte.“',
  ],
  vocab: [
    {
      id: 'mlh-1',
      de: 'Ich hätte gern…',
      en: 'I would like…',
      note: 'The politest everyday order. Works at every counter.',
    },
    {
      id: 'mlh-2',
      de: 'die Speisekarte',
      en: 'the menu',
      note: '„Die Speisekarte, bitte.“ — three words, done.',
    },
    {
      id: 'mlh-3',
      de: 'zum Mitnehmen',
      en: 'to take away',
      note: 'The opposite is „hier essen“ (eat in).',
    },
    {
      id: 'mlh-4',
      de: 'Was empfehlen Sie?',
      en: 'What do you recommend?',
      note: 'Turns an order into a short conversation.',
    },
    {
      id: 'mlh-5',
      de: 'Haben Sie etwas Vegetarisches?',
      en: 'Do you have something vegetarian?',
      note: 'Swap in „Veganes“ or „ohne Nüsse“ as needed.',
    },
    {
      id: 'mlh-6',
      de: 'Mit Karte, bitte.',
      en: 'By card, please.',
      note: 'Or „Bar, bitte.“ — plenty of places are still cash only.',
    },
    {
      id: 'mlh-7',
      de: 'Zahlen, bitte.',
      en: 'The bill, please.',
      note: 'For table service. At a counter you pay up front.',
    },
    {
      id: 'mlh-8',
      de: "Das war's, danke.",
      en: "That's all, thanks.",
      note: 'Signals your order is finished so they can total it up.',
    },
  ],
  conversationSimulation: [
    {
      id: 'mlh-c1',
      speaker: 'partner',
      de: 'Hallo! Was darf es sein?',
      en: 'Hello! What can I get you?',
    },
    {
      id: 'mlh-c2',
      speaker: 'you',
      de: 'Hallo! Ich hätte gern die Gemüsesuppe, bitte.',
      en: 'Hello! I would like the vegetable soup, please.',
    },
    {
      id: 'mlh-c3',
      speaker: 'partner',
      de: 'Gerne. Und etwas zu trinken?',
      en: 'Sure. And something to drink?',
    },
    {
      id: 'mlh-c4',
      speaker: 'you',
      de: 'Ein Wasser, bitte. Was empfehlen Sie noch?',
      en: 'A water, please. What else do you recommend?',
    },
    {
      id: 'mlh-c5',
      speaker: 'partner',
      de: 'Die Brezel ist ganz frisch.',
      en: 'The pretzel is very fresh.',
    },
    {
      id: 'mlh-c6',
      speaker: 'you',
      de: 'Dann eine Brezel dazu. Haben Sie etwas Vegetarisches als Nachtisch?',
      en: 'A pretzel with it, then. Do you have something vegetarian for dessert?',
    },
    {
      id: 'mlh-c7',
      speaker: 'partner',
      de: 'Ja, den Apfelkuchen. Zum Mitnehmen oder hier essen?',
      en: 'Yes, the apple cake. To take away or eat in?',
    },
    {
      id: 'mlh-c8',
      speaker: 'you',
      de: "Zum Mitnehmen, bitte. Das war's, danke.",
      en: "To take away, please. That's all, thanks.",
    },
    {
      id: 'mlh-c9',
      speaker: 'partner',
      de: 'Macht neun Euro achtzig.',
      en: "That'll be nine euros eighty.",
    },
    {
      id: 'mlh-c10',
      speaker: 'you',
      de: 'Mit Karte, bitte.',
      en: 'By card, please.',
    },
    {
      id: 'mlh-c11',
      speaker: 'partner',
      de: 'Klar. Guten Appetit!',
      en: 'Sure. Enjoy your meal!',
    },
  ],
  practiceQuestions: [
    {
      id: 'mlh-q1',
      kind: 'multiple-choice',
      prompt:
        'The person behind the counter asks: „Zum Mitnehmen oder hier essen?“ What are they asking?',
      options: ['Takeaway or eat in', 'Cash or card', 'Whether you want a bag'],
      answerIndex: 0,
      explanation: 'mitnehmen = to take with you. „Hier essen“ = eat in.',
    },
    {
      id: 'mlh-q2',
      kind: 'fill-blank',
      prompt: 'Complete the polite order.',
      sentence: 'Ich ___ gern einen Kaffee, bitte.',
      answer: 'hätte',
      alternatives: ['hatte'],
      explanation: '„Ich hätte gern“ — subjunctive, and the reason it sounds polite.',
    },
    {
      id: 'mlh-q3',
      kind: 'write-sentence',
      prompt: 'Write the real order you will place today, and ask for it to go.',
      mustInclude: ['bitte', 'Mitnehmen'],
      sample: 'Ich hätte gern einen Kaffee, bitte. Zum Mitnehmen.',
      explanation: 'Two short sentences beat one complicated one at a busy counter.',
    },
  ],
  badge: {
    title: 'Alltagsheld',
    emoji: '🥨',
    description: 'Ordered and paid for something entirely in German.',
  },
};
