import type { Mission } from '@/lib/types';

export const meetYourPeople: Mission = {
  id: 'meet-your-people',
  title: 'Meet your people',
  tagline: 'Start a conversation and suggest a plan without overthinking it.',
  category: 'Making friends',
  icon: 'users',
  level: 'advanced',
  minutes: 25,
  accent: 'magenta',
  where: 'A Sportverein session, a language café, or your building courtyard.',
  reflectionFocus: 'start a conversation with someone new',
  realLifeSteps: [
    'Go somewhere people repeat — a club, a class, a café you can return to.',
    'Open with an observation, not a lesson: „Kommst du oft hierher?“',
    'Ask one follow-up question about them before talking about yourself.',
    'Suggest something concrete with a day in it: „Passt dir Samstag?“',
    'Swap numbers, or agree when you will both be back.',
  ],
  vocab: [
    {
      id: 'myp-1',
      de: 'Kommst du oft hierher?',
      en: 'Do you come here often?',
      note: 'The easiest opener when you are both just standing around.',
    },
    {
      id: 'myp-2',
      de: 'Ich bin neu in der Stadt.',
      en: "I'm new in the city.",
      note: 'Buys patience, and usually a tip about the neighbourhood.',
    },
    {
      id: 'myp-3',
      de: 'Wie lange wohnst du schon hier?',
      en: 'How long have you lived here?',
      note: 'German keeps this in the present tense with „schon“.',
    },
    {
      id: 'myp-4',
      de: 'Hast du Lust auf…?',
      en: 'Do you feel like…?',
      note: '„Hast du Lust auf einen Kaffee?“ — low pressure invitation.',
    },
    {
      id: 'myp-5',
      de: 'Wollen wir…?',
      en: 'Shall we…?',
      note: '„Wollen wir mal zusammen laufen gehen?“',
    },
    {
      id: 'myp-6',
      de: 'Passt dir Samstag?',
      en: 'Does Saturday work for you?',
      note: 'Naming a day is what turns a nice chat into a plan.',
    },
    {
      id: 'myp-7',
      de: 'Ich schreibe dir.',
      en: "I'll text you.",
      note: 'Closes the loop before you walk away.',
    },
    {
      id: 'myp-8',
      de: 'Das klingt gut.',
      en: 'That sounds good.',
      note: 'Accepts an invitation without a speech.',
    },
  ],
  conversationSimulation: [
    {
      id: 'myp-c1',
      speaker: 'partner',
      de: 'Bist du das erste Mal hier?',
      en: 'Is this your first time here?',
    },
    {
      id: 'myp-c2',
      speaker: 'you',
      de: 'Ja, ich bin neu in der Stadt. Kommst du oft hierher?',
      en: "Yes, I'm new in the city. Do you come here often?",
    },
    {
      id: 'myp-c3',
      speaker: 'partner',
      de: 'Jeden Donnerstag. Wie lange wohnst du schon in Hamburg?',
      en: 'Every Thursday. How long have you been living in Hamburg?',
    },
    {
      id: 'myp-c4',
      speaker: 'you',
      de: 'Seit drei Monaten. Mein Deutsch ist noch langsam, aber ich übe.',
      en: "For three months. My German is still slow, but I'm practising.",
    },
    {
      id: 'myp-c5',
      speaker: 'partner',
      de: 'Klingt doch super. Sag einfach, wenn ich langsamer sprechen soll.',
      en: 'Sounds great. Just say if I should speak more slowly.',
    },
    {
      id: 'myp-c6',
      speaker: 'you',
      de: 'Danke. Hast du Lust auf einen Kaffee nach dem Training?',
      en: 'Thanks. Do you feel like a coffee after the session?',
    },
    {
      id: 'myp-c7',
      speaker: 'partner',
      de: 'Heute muss ich los, aber gerne ein andermal.',
      en: 'I have to go today, but gladly another time.',
    },
    {
      id: 'myp-c8',
      speaker: 'you',
      de: 'Passt dir Samstag am Nachmittag?',
      en: 'Does Saturday afternoon work for you?',
    },
    {
      id: 'myp-c9',
      speaker: 'partner',
      de: 'Samstag passt. Schreib mir einfach.',
      en: 'Saturday works. Just text me.',
    },
    {
      id: 'myp-c10',
      speaker: 'you',
      de: 'Mache ich. Ich schreibe dir. Bis Samstag!',
      en: "I will. I'll text you. See you Saturday!",
    },
  ],
  practiceQuestions: [
    {
      id: 'myp-q1',
      kind: 'multiple-choice',
      prompt: '„Hast du Lust auf einen Kaffee?“ — what is happening here?',
      options: [
        'An invitation you can accept with „Das klingt gut.“',
        'A complaint about the coffee',
        'A question about where you live',
      ],
      answerIndex: 0,
      explanation: '„Lust auf“ + noun is the standard low-pressure invitation.',
    },
    {
      id: 'myp-q2',
      kind: 'fill-blank',
      prompt: 'Complete the line that buys you patience.',
      sentence: 'Ich bin ___ in der Stadt.',
      answer: 'neu',
      alternatives: [],
      explanation: 'Say it early. Most people slow down straight away.',
    },
    {
      id: 'myp-q3',
      kind: 'write-sentence',
      prompt: 'Write an invitation with a specific day in it.',
      mustInclude: ['Samstag'],
      sample: 'Wollen wir am Samstag einen Kaffee trinken?',
      explanation: 'A day makes it a plan. „Mal irgendwann“ never happens.',
    },
  ],
  badge: {
    title: 'Anschluss',
    emoji: '🤝',
    description: 'Started a conversation with someone new and suggested a plan.',
  },
};
